icon.file.extensions=
icon.file.files=

icon.pdf.extensions=pdf
icon.pdf.files=

icon.word.extensions=doc,docx
icon.word.files=

icon.excel.extensions=xls,xlsx
icon.excel.files=

icon.image.extensions=png,jpg,jpeg,gif
icon.image.files=

icon.zip.extensions=zip
icon.zip.files=